### ISSUE TITLE
Make a submission backup

### ISSUE THREAD

**Issue by verndrade** [SyllabiShare/syllabi-share#46]
Write an admin service to export the submissions metadata to a programmatic form (like JSON) which can re-make the submissions in case of deletion or corruption

**Comment by verndrade** [comment]
current workaround: 
go to heroku dashboard console
python manage.py shell >> dump.txt
import models and iterate through model.objects.all() and print them (they will go into dump.txt)
after all are printed exit the shell
clone a git repo which you can add the dump file to
add dump.txt to the repo, commit, and push
access the repo in github to see the dump

Probably could have everything be downloaded through a button on the admin console, but I wanted to find the most convoluted way of doing it 🤡

**Comment by winstliu** [comment]
@verndrade in the future: `python manage.py dumpdata >> db.json`
