### ISSUE TITLE
Back Button Navigator should not be at bottom of left

### ISSUE THREAD

**Issue by kyawzazaw** [SyllabiShare/syllabi-share#61]
The placement seems off to me. And it is too prominent.

**Comment by winstliu** [comment]
I was considering...just getting rid of those two buttons. Yes/no?

**Comment by kyawzazaw** [comment]
Yes, instead of back button maybe a directory hierachy-like cicakble would be great.

See example here:
![navg](https://user-images.githubusercontent.com/10335802/83318844-29024080-a1fe-11ea-9bd0-59a8f46bedd9.png)

So it could be like
Nice College\department\course for example

**Comment by winstliu** [comment]
Good idea. I can experiment with that and see how it turns out.

For self: https://getbootstrap.com/docs/4.5/components/breadcrumb/

**Comment by winstliu** [comment]
Discussion on Slack
![replace-back-with-browse](https://user-images.githubusercontent.com/2766036/85241830-25339980-b40b-11ea-834d-9306fa1aa681.png)
