### ISSUE TITLE
Split Submission "course" field into "dept" and "number"

### ISSUE THREAD

**Issue by winstliu** [SyllabiShare/syllabi-share#63]
We already have `dept`, but `course` is the whole thing and it's redundant. Splitting it will allow us to perform more useful querying and filtering, and make it easier to add course subpages like `/dept/course`.

**Comment by winstliu** [comment]
If this is a yes, then we'll need to investigate what needs to be done to transfer the existing submissions.

**Comment by verndrade** [comment]
transferring existing ones is pretty easy, just add a coursenumber field, and populate it in the shell with course.split(' ')[1] then deleting the course field. I guess the benefit of separating them is querying classes about 3000 or somethings
