### ISSUE TITLE
ASTR 1290 syllabus not uploaded correctly?

### ISSUE THREAD

**Issue by mengsarah** [SyllabiShare/syllabi-share#8]
On Firefox 76.0.1, the ASTR 1290 syllabus currently listed won't load on either https://syllabi-share.herokuapp.com/ or when you click the giant arrow to open the PDF itself in the browser (no pages shown, just the blank dark gray background of the PDF viewer). Firefox displays a yellow bar at the top of the page saying "This PDF document might not be displayed correctly."

**Comment by verndrade** [comment]
After some initial investigation. This seems to occur on all browsers. However, the link to the file in the S3 bucket seems to be working which is peculiar. I will look into it further

**Comment by winstliu** [comment]
LOL, it's the login-required HTML page for Collab 🙃
![login-required](https://user-images.githubusercontent.com/2766036/82854970-fa235c00-9ed7-11ea-8bc3-17dc600530e7.png)

Gotta check those MIME types Vernon!! Check out libmagic (`python-magic`).

**Comment by verndrade** [comment]
took it down
